version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: timeplus-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - timeplus-network

  nginx:
    image: nginx:alpine
    container_name: timeplus-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - timeplus-network

  mysql:
    image: mysql:8.0
    container_name: timeplus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: timeplus
      MYSQL_USER: timeplus
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - timeplus-network

  mailhog:
    image: mailhog/mailhog
    container_name: timeplus-mailhog
    tty: true

    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure

    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null

    networks:
      - timeplus-network

networks:
  timeplus-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
